version: '3.8'

services:
  postgres:
    image: ankane/pgvector:latest  # pgvector가 이미 설치된 이미지
    container_name: local-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
