version: '3.8'

services:
  mysql:
    image: mysql:8.0           # MySQL 이미지, 최신 안정 버전
    container_name: local-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234  # MySQL 루트 비밀번호
      MYSQL_DATABASE: testdb       # 생성할 기본 데이터베이스 이름
      MYSQL_PASSWORD: 1234       # 추가 사용자의 비밀번호
    ports:
      - "3306:3306"             # 호스트와 컨테이너의 포트를 매핑
    volumes:
      - mysql_data:/var/lib/mysql  # 데이터 영구 저장소 마운트

volumes:
  mysql_data:
    driver: local
